/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bifurcacionsimple;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Ventana extends javax.swing.JFrame {

    private Bifurcacion bifu = new Bifurcacion();
      
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbEntero = new javax.swing.JTextField();
        tbCaracter = new javax.swing.JTextField();
        bEntero = new javax.swing.JButton();
        bCaracter = new javax.swing.JButton();
        tbDecimal = new javax.swing.JTextField();
        bDecimal = new javax.swing.JButton();
        tbCadena = new javax.swing.JTextField();
        bCadena = new javax.swing.JButton();
        tbLogico = new javax.swing.JTextField();
        bLogico = new javax.swing.JButton();
        lDecimal = new javax.swing.JLabel();
        lEntero = new javax.swing.JLabel();
        lCaracter = new javax.swing.JLabel();
        lCadena = new javax.swing.JLabel();
        lLogico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bifurcación Simple if..else");
        setResizable(false);

        bEntero.setText("Verificar");
        bEntero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnteroActionPerformed(evt);
            }
        });

        bCaracter.setText("Verificar");
        bCaracter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCaracterMouseClicked(evt);
            }
        });

        bDecimal.setText("Verificar");
        bDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDecimalMouseClicked(evt);
            }
        });

        bCadena.setText("Verificar");
        bCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadenaActionPerformed(evt);
            }
        });

        bLogico.setText("Verificar");
        bLogico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogicoActionPerformed(evt);
            }
        });

        lDecimal.setText("Digite su estatura:");

        lEntero.setText("Digite su edad:");

        lCaracter.setText("Escriba el tipo de beca: A, B o C:");

        lCadena.setText("Escriba su contraseña:");

        lLogico.setText("¿Es becado? Sí-True No-False");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lCadena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lDecimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lEntero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lLogico, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(lCaracter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbLogico, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbEntero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLogico, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCadena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCaracter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bEntero, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bCadena)
                                .addComponent(tbCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lCadena))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bEntero)
                                            .addComponent(tbEntero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bDecimal)
                                            .addComponent(tbDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lEntero)
                                        .addGap(15, 15, 15)
                                        .addComponent(lDecimal)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tbCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lCaracter))
                                    .addComponent(bCaracter))
                                .addGap(29, 29, 29)))
                        .addComponent(bLogico))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tbLogico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lLogico)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnteroActionPerformed
        bifu.setEntero(Integer.parseInt(this.tbEntero.getText()));
        if(bifu.getEntero()>=18){
            JOptionPane.showMessageDialog(this,
                  "Usted es mayor de edad",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
        else{
             JOptionPane.showMessageDialog(this,
                  "Usted es menor de edad",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_bEnteroActionPerformed

    private void bDecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDecimalMouseClicked
        bifu.setDecimal(Float.parseFloat(this.tbDecimal.getText()));
        if(bifu.getDecimal()<=160.0f){
            JOptionPane.showMessageDialog(this,
                  "Usted es de baja estatura",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,
                  "Usted es de mediana o alta estatura",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bDecimalMouseClicked

    private void bCaracterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCaracterMouseClicked
        bifu.setCaracter(this.tbCaracter.getText().charAt(0));
        if(bifu.getCaracter()!='A' && bifu.getCaracter()!='a'){
            JOptionPane.showMessageDialog(this,
                  "Su reunión es la próxima semana",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,
                  "Usted tiene cita el día de hoy",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bCaracterMouseClicked

    private void bCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadenaActionPerformed
        this.bifu.setCadena(this.tbCadena.getText());
        if(bifu.getCadena().equals("123.abc")){
            JOptionPane.showMessageDialog(this,
                  "Acceso concedido",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,
                  "Acceso denegado",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bCadenaActionPerformed

    private void bLogicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogicoActionPerformed
        this.bifu.setLogico(Boolean.parseBoolean(this.tbLogico.getText()));
        if(bifu.getLogico()==true){
            JOptionPane.showMessageDialog(this,
                  "Felicidades",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,
                  "Puedes optar a una...",
                  "Bifurcación simple",
                  JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bLogicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadena;
    private javax.swing.JButton bCaracter;
    private javax.swing.JButton bDecimal;
    private javax.swing.JButton bEntero;
    private javax.swing.JButton bLogico;
    private javax.swing.JLabel lCadena;
    private javax.swing.JLabel lCaracter;
    private javax.swing.JLabel lDecimal;
    private javax.swing.JLabel lEntero;
    private javax.swing.JLabel lLogico;
    private javax.swing.JTextField tbCadena;
    private javax.swing.JTextField tbCaracter;
    private javax.swing.JTextField tbDecimal;
    private javax.swing.JTextField tbEntero;
    private javax.swing.JTextField tbLogico;
    // End of variables declaration//GEN-END:variables
}
